export { defineFrontendAdapter } from "./contract/adapter.js";
export {
  VextApiError,
  createVextApiClient,
  isVextApiError,
  type VextApiClient,
  type VextApiClientOptions,
  type VextApiRequestOptions,
  type VextApiRequestOptionsFor,
  type VextApiRouteType,
} from "./contract/api-client.js";
export type {
  ResolvedVextFrontendConfig,
  ResolvedVextFrontendSeoConfig,
  VextClientContract,
  VextClientResponseContract,
  VextClientRouteContract,
  VextClientRouteMethod,
  VextClientSchemaReference,
  VextFrontendAdapter,
  VextFrontendBuildConfig,
  VextFrontendBuildTargetConfig,
  VextFrontendConfig,
  VextFrontendDeployConfig,
  VextFrontendDevConfig,
  VextFrontendErrorPagesConfig,
  VextFrontendFramework,
  VextFrontendI18nConfig,
  VextFrontendJscssConfig,
  VextFrontendManifest,
  VextFrontendManifestAsset,
  VextFrontendImageFormat,
  VextFrontendMediaConfig,
  VextFrontendMediaFontsConfig,
  VextFrontendMediaImagesConfig,
  VextFrontendMode,
  VextFrontendPagesConfig,
  VextFrontendRenderConfig,
  VextFrontendRobotsConfig,
  VextFrontendSeoConfig,
  VextFrontendSitemapConfig,
  VextFrontendStaticArtifact,
  VextFrontendStaticManifest,
  VextFrontendSpaFallbackConfig,
  VextFrontendSpaFallbackScope,
  VextFrontendStylesConfig,
  VextFrontendUserConfig,
  VextRouteFreshnessIdentity,
  VextRouteFrontendSeoOptions,
  VextRouteLayoutIdentity,
  VextRouteResponseSchemaV1,
  VextRouteSchemaContractV1,
  VextSchemaIRV1,
  VextOpenGraphMetadata,
  VextRenderSeoOptions,
  VextRobotsGroup,
  VextSeoAlternate,
  VextSeoImage,
  VextSeoMetadata,
  VextSeoRobotsDirective,
  VextSitemapEntriesContext,
  VextSitemapEntriesProvider,
  VextSitemapEntry,
  VextTwitterMetadata,
} from "./contract/types.js";
export {
  defineFont,
  defineImageLoader,
  Image,
  type VextImageProps,
} from "./media/index.js";
export type {
  VextDefinedFont,
  VextFontDefinition,
  VextFontFallbackMetrics,
  VextFontVariationAxis,
  VextFontVariationAxisRange,
  VextFrontendMediaFont,
  VextFrontendMediaImage,
  VextFrontendMediaManifest,
  VextFrontendMediaVariant,
  VextImageRemoteLoader,
  VextImageRemoteLoaderInput,
  VextMediaRasterFormat,
} from "./media/types.js";
export {
  createFrontendRenderMiddleware,
  createFrontendRenderer,
} from "./runtime/renderer.js";
export {
  createFreshnessKeyDigest,
  getFrontendFreshnessStore,
  invalidateFrontendFreshness,
  VextFrontendFreshnessStore,
  type VextFrontendFreshnessEntry,
  type VextFrontendFreshnessInvalidation,
  type VextFrontendFreshnessInvalidationResult,
  type VextFrontendFreshnessKey,
  type VextFrontendFreshnessReadResult,
  type VextFrontendFreshnessResponse,
  type VextFrontendFreshnessStoreOptions,
  type VextFrontendFreshnessWriteInput,
} from "./runtime/freshness.js";
export {
  buildFrontendDeployManifest,
  createFilesystemDeployAdapter,
  createFrontendDeployPlan,
  createMockDeployAdapter,
  deployFrontendAssets,
  joinUploadKey,
} from "./deploy/index.js";
export {
  VextRenderContext,
  VextRenderProvider,
  useVextI18n,
  type VextI18nContextValue,
} from "./runtime/i18n.js";
export {
  Form,
  Link,
  VextBrowserRuntime,
  VextPageResultError,
  configureVextBrowserRuntime,
  navigate,
  prefetch,
  revalidate,
  useFetcher,
  useNavigation,
  useRouteData,
  type ConfigureVextBrowserRuntimeOptions,
  type VextBrowserEnvironment,
  type VextBrowserRuntimeDiagnostics,
  type VextFetcher,
  type VextFetcherSnapshot,
  type VextFormProps,
  type VextLinkProps,
  type VextNavigateOptions,
  type VextNavigationPhase,
  type VextNavigationSnapshot,
  type VextPrefetchOptions,
  type VextRevalidateTarget,
  type VextSubmitOptions,
} from "./runtime/navigation.js";
export {
  VEXT_BUILD_ID_HEADER,
  VEXT_NAVIGATION_HEADER,
  VEXT_PAGE_MEDIA_TYPE,
  VEXT_PAGE_PROTOCOL_VERSION,
  isVextPageEnvelopeV1,
  type VextPageEnvelopeCacheV1,
  type VextPageEnvelopeErrorResultV1,
  type VextPageEnvelopePageResultV1,
  type VextPageEnvelopeRedirectResultV1,
  type VextPageEnvelopeResultV1,
  type VextPageEnvelopeV1,
} from "./contract/page-envelope.js";
export type {
  VextFrontendDeployManifest,
  VextFrontendDeployManifestAsset,
  VextFrontendDeployPlan,
  VextFrontendDeployPlanItem,
  VextFrontendDeployResult,
  VextFrontendDeployUploadAdapter,
  VextFrontendDeployUploadAdapterInput,
  VextFrontendDeployUploadAdapterName,
  VextFrontendDeployUploadAdapterResult,
  VextFrontendDeployUploadConfig,
} from "./contract/types.js";
